task_2_4_1
evangelionexpert/OOP pull request #15
Opened 2023-05-15 18:53 UTC by evangelionexpert

2023-05-22 19:29 UTC, evangelionexpert commented
Поскольку прогон всех репозиториев (практически, пока что не добавил еще трех человек) занимает ни много ни мало практически 15 минут, прикрепляю пример отчета (на данный момент он сыроват, к тому же доступен только вывод в stdout/stderr/другой PrintStream).

![image](https://github.com/evangelionexpert/oop/assets/91373209/ff7adb40-bdc7-42c0-bda9-d8c4c9222f09)

2023-05-30 06:28 UTC, evangelionexpert commented
Поскольку лаба разрослась больше ожидаемого, добавил в README.md немного пояснений, прошу обратить внимание при проверке.

2023-05-30 06:29 UTC, evangelionexpert commented
Примеры вывода в html (планирую добавить также подробный вывод всей информации по одному студенту/по одному assignmentstatus'у)
![image](https://github.com/evangelionexpert/oop/assets/91373209/403ceb4d-4c24-44c2-9dc7-3222956a25ba)
![image](https://github.com/evangelionexpert/oop/assets/91373209/c0998244-25cf-4137-beda-4c16dafae0b6)

2023-06-02 20:17 UTC, MihailCCfit commented
Порекомендовал бы разделить evaluate с git. Наверное это немного разные процессы, которые хотелось бы разделить. Ведь запуск билдов, джакоко; скачивание репы и checkout; выставление оценки - разные вещи. Думаю, это улучшит логику и сделает код полегче для модификации и расширения.

2023-06-02 20:43 UTC, MihailCCfit requested changes

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/dsl_config/progress.groovy
> +        forTask('task_1_2_1') {
Какая-то длинная портянка. Хотел бы порекомендовать использовать внутри конфига груви. Можно выше определить словарь, его легко оформить будет `['task_1_2_1':'Task_1_2_1', ...]`, а затем сделать for внутри forStudent. А если у нескольких студентов так повторяется, то можно сделать выше и список студентов и по нему тоже for. Итого просто с помощью ТОЛЬКО GROOVY, можно уменьшить писанину. Попробуй!

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/dsl_config/schedule.groovy
> +    assignment('task_1_1_1') {
Наверное удобно было бы так же иметь функцию, что выставляется первый дедлайн + его смещение, длительность. Так проще записывать будет человеку конфиги

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/dsl_config/schedule.groovy
> +    lessonAt '2022-09-05'
Добавить константу смещения и функцию, которая заполняет интервал. Мне кажется было бы удобно

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/examples/evaluation.html
> +<style>
Попробуй найти ещё стили прикольные, там есть, чтобы например каждая четная линия немного другого цвета была

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/consoleinterpreter/command/Command.java
> +@Getter
Если поля final, то мб без геттеров их получать? Ну тут я увы не шарю, как лучше.

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/consoleinterpreter/commandprovider/AbstractCommandProvider.java
> +public abstract class AbstractCommandProvider {
Получается это калькулятор? А он полон по Тьюрингу?

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/consoleinterpreter/processor/Processor.java
> +public class Processor {
+

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/Application.java
> +    public static final String CONFIGURATION_SCRIPT_PATH = DSL_FOLDER_PATH + "configuration.groovy";
А как тебе идея иметь конфиг где находятся конфиги? Или же ещё функцию include сделать. Ладно, бредятина

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/Application.java
> +        var entity = SubjectDataEntitySerializer.deserialize("privet.dat");
var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,var, var, var ,var ,var,

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/dto/SubjectDataDto.java
> +public class SubjectDataDto { // TODO rename // TODO у всех классов менять аннотации а то какой то всратыш уродился
Сильный класс. Остался один вопрос. Почему же это не любимый record?

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/dto/configuration/ConfigurationDto.java
> +public class ConfigurationDto {
record?

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/dto/course/CourseDto.java
> +        groovyDelegate(tasks, closure);
Можно не заводить отдельный класс под это. А прост поставить, чтобы этот же объект и обрабатывал groovyDelegate(this, closure);
Тогда это избавить от лишней обвертки. Не, ну если идея была обернуть List<TaskDto> в TaskList, то ладно.

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/dto/group/GroupDto.java
> +import static ru.nsu.fit.smolyakov.evaluationsuite.util.DslDelegator.groovyDelegate;
а

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/dto/group/GroupDto.java
> +    public static class StudentList {
Аналогично предыдущему подумать

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/dto/group/StudentDto.java
> +@RequiredArgsConstructor
Блин, ну это сильно. Не сделать самим один конструктор из нужно поля. А пометить, что не должно быть наллом, а потом указать, что @RequiredArgsConstructor. Есть человек, который имеет что-то против аннотаций и говорит, что ему они не нравятся

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/dto/progress/OverriddenTaskDto.java
> +@RequiredArgsConstructor
аоаоаоаоаоаоаоаоаоаооаоаоаоа

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/dto/schedule/AssignmentDto.java
> +public class AssignmentDto {
О, здесь уже без собаки, круто

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/dto/schedule/LessonDto.java
> +public class LessonDto {
Честно, сильно. Желаю сделать рекорд, чтобы не выглядело настолько сильно

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/entity/group/Group.java
> +@RequiredArgsConstructor
Да

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/entity/group/Student.java
> +@NonNull
Что нот налл?

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/evaluator/Evaluator.java
> +    public final String TMP_DIR = ".checks_tmp/" + System.currentTimeMillis() + "/";
Настолько временная?

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/evaluator/Evaluator.java
> +public class Evaluator {
Замечание описано в комментарии вне ревью

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/evaluator/Evaluator.java
> +        var jacocoReportXml = new File(pathToTask + "/build/reports/jacoco/test/jacocoTestReport.xml");
var ... = ...

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/evaluator/JacocoReportParser.java
> +public class JacocoReportParser {
Понравилось, кода меньше чем собак

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/util/SubjectDataDtoToEntity.java
> +@RequiredArgsConstructor
да

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/util/SubjectDataDtoToEntity.java
> +        return Assignment.builder()
Выглядит сильно

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/util/SubjectDataDtoToEntity.java
> +            .toList(); // СПИСОК ЗАДАЧ
Я думал массив

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/util/SubjectDataDtoToEntity.java
> +            .toList();
Список студентов

2023-06-02 20:43 UTC, MihailCCfit commented on task_2_4_1/src/main/java/ru/nsu/fit/smolyakov/evaluationsuite/util/SubjectDataDtoToEntity.java
> +                    Optional.ofNullable(overriddenTaskInfoDto.getIdentifierAlias())
Что-то без функторов выглядит так себе. Писал бы ты на котлине, тогда понял бы смысл этих строк. А так, проверка на null, выглядила бы короче, да и работала бы быстрее

2023-06-23 16:30 UTC, merged