task_1_2_1
evangelionexpert/OOP pull request #3
Opened 2022-09-22 17:20 UTC by evangelionexpert

2022-10-03 11:30 UTC, molo4evan requested changes

2022-10-03 11:30 UTC, molo4evan commented on task_1_2_1/src/main/java/ru/nsu/fit/smolyakov/stack/Stack.java
> +    private class Parameters {
Зачем вообще вводить внутренний класс? Можно просто объявить константы в теле основного класса

2022-10-03 11:30 UTC, molo4evan commented on task_1_2_1/src/main/java/ru/nsu/fit/smolyakov/stack/Stack.java
> +            push(anotherStack.arr[i]);
Ты имеешь доступ к внутренней структуре стека, перекладывание по 1 элементу очень неэффективно

2022-10-03 11:30 UTC, molo4evan commented on task_1_2_1/src/main/java/ru/nsu/fit/smolyakov/stack/Stack.java
> +        size -= elemAmount;
Еще важно занулить ссылки на удаленные элементы во внутреннем массиве для корректной работы GC

2022-10-03 11:30 UTC, molo4evan commented on task_1_2_1/src/test/java/ru/nsu/fit/smolyakov/stack/StackTest.java
> +class TestLists {
В 1 файле - только 1 top-level класс

2022-10-03 11:30 UTC, molo4evan commented on task_1_2_1/src/test/java/ru/nsu/fit/smolyakov/stack/StackTest.java
> +    static String lonelyString = "haha steak is not empty haha";
Стейк не пуст? :)

2022-10-04 03:06 UTC, evangelionexpert commented on task_1_2_1/src/main/java/ru/nsu/fit/smolyakov/stack/Stack.java
> +    private class Parameters {
исправлено

2022-10-04 03:07 UTC, evangelionexpert commented on task_1_2_1/src/main/java/ru/nsu/fit/smolyakov/stack/Stack.java
> +            push(anotherStack.arr[i]);
исправлено

2022-10-04 03:07 UTC, evangelionexpert commented on task_1_2_1/src/main/java/ru/nsu/fit/smolyakov/stack/Stack.java
> +        size -= elemAmount;
исправил

2022-10-04 03:07 UTC, evangelionexpert commented on task_1_2_1/src/test/java/ru/nsu/fit/smolyakov/stack/StackTest.java
> +class TestLists {
исправил

2022-10-04 03:07 UTC, evangelionexpert commented on task_1_2_1/src/test/java/ru/nsu/fit/smolyakov/stack/StackTest.java
> +    static String lonelyString = "haha steak is not empty haha";
поменял на грустный смайлик :<

2022-10-08 20:15 UTC, molo4evan commented
**Треды не резолвятся студентом**

**Треды может резолвить только преподаватель, если в них прямо не сказано иного**

**С третьей лабы за это буду отнимать баллы**

2022-10-09 20:34 UTC, merged